// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.Clear_Config_Value")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.Set_Environment_Variable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.Throws_Exception_If_VariableName_Is_Empty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.Config_File_Entry_Correctly_Parsed(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.Set_Environment_Variable_Variable_Cant_Be_Null(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.Set_Environment_Variable_Variable_Must_Be_Valid_Format(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.Set_Variable_Correctly_Appends_To_File(System.String,System.String)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.Get_Entry_By_Name_True_When_Entry_Exists_And_False_When_Not(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Compiler", "CS8600:Converting null literal or possible null value to non-nullable type.", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.Clear_Config_Value")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.Clear_Config_Value")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Compiler", "CS8600:Converting null literal or possible null value to non-nullable type.", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.Set_Environment_Variable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.Set_Environment_Variable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Compiler", "CS8600:Converting null literal or possible null value to non-nullable type.", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.Get_Entry_By_Name_True_When_Entry_Exists_And_False_When_Not(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Compiler", "CS8600:Converting null literal or possible null value to non-nullable type.", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.Set_Variable_Correctly_Appends_To_File(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.Set_Variable_Correctly_Appends_To_File(System.String,System.String)")]